### ISSUE TITLE
OpenHAB 2.1.0 - Binding fails to load on first use

### ISSUE THREAD

**Issue by nwootton** [Nebula83/openhab2-addons#11]
Clean version of OH2.1 via .zip from openhab.org
Expanded and then the EvoHome binding copied into the addons dir. Simplified conf as used before results in the binding not loading with the following error repeating:

```
2017-06-29 08:31:05.061 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/Users/nick/openhab/runtimes/openhab-2.1.0/addons/org.openhab.binding.evohome-2.1.1-SNAPSHOT-2.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.evohome [9]
  Unresolved requirement: Import-Package: com.google.common.collect

	at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)[4:org.apache.felix.fileinstall:3.5.6]
 ```

Shutting down OH2.1 and then restarting allows the binding to work without a single error appearing in the logs. This might be the same issue as I spoke to you about before (https://community.openhab.org/t/new-evohome-binding/7696/96) with the loads of errors on a clean install. Last time the binding would error but still appear. Now it errors, and then totally fails to appear until the OH runtime is restarted.

Running on Mac OSX 10.11.6

Update: I looked at the error log from the previous 'lots of errors at start' post on the OH forum. There are a lot of different errors in that version, in this case it is the same error over and over.

**Comment by Nebula83** [comment]
Hi Nick, I haven't tried it with OH2.1 yet, so I don't know what it does for me. I did look into the 'lots of errors at start' issue, but I couldn't find a lead as to where to look. It has to do with the dependencies of the binding for sure, but I don't know what to change/improve to make it work out-of-the box. I'll investigate more when I have the time.

**Comment by Nebula83** [comment]
Tested with both 2.1.0 and 2.2.0. Can't repoduce so closing the issue. Please re-open if you see it again.

**Comment by Nebula83** [comment]
Tested with both 2.1.0 and 2.2.0. Can't repoduce so closing the issue. Please re-open if you see it again.
