### ISSUE TITLE
java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header

### ISSUE THREAD

**Issue by Nebula83** [Nebula83/openhab2-addons#3]
2017-05-23 14:55:49.807 [ERROR] [ome.internal.api.models.v2.ApiAccess] - Error in handling request
java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:653)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.openhab.binding.evohome.internal.api.models.v2.ApiAccess.doRequest(ApiAccess.java:58)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.internal.api.models.v2.ApiAccess.doAuthenticatedRequest(ApiAccess.java:89)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.internal.api.EvohomeApiClientV2.requestLocationsStatus(EvohomeApiClientV2.java:83)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.internal.api.EvohomeApiClientV2.update(EvohomeApiClientV2.java:149)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.handler.EvohomeGatewayHandler.update(EvohomeGatewayHandler.java:129)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.handler.EvohomeGatewayHandler.access$0(EvohomeGatewayHandler.java:122)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at org.openhab.binding.evohome.handler.EvohomeGatewayHandler$1.run(EvohomeGatewayHandler.java:116)[215:org.openhab.binding.evohome:2.1.0.201705221349]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_121]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_121]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
Caused by: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.onComplete(AuthenticationProtocolHandler.java:113)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:453)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:400)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:266)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1403)[72:org.eclipse.jetty.http:9.2.19.v20160908]
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1245)[72:org.eclipse.jetty.http:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:89)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:123)[70:org.eclipse.jetty.client:9.2.19.v20160908]
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[73:org.eclipse.jetty.io:9.2.19.v20160908]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.19.v20160908]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.19.v20160908]

**Comment by Nebula83** [comment]
This is due to the OAUTH token expiring, fix is in the making

**Comment by Nebula83** [comment]
Update: it has been running for 24 hours with 15 second updates, re-logging  in for every request. It will be merged soon
